sudo: required
dist: trusty
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libboost-dev
            - libboost-chrono-dev
            - libboost-system-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

