# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
        packages:
            - gcc-5
            - g++-5
            - clang-3.6
            - cmake
            - cmake-data

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
